config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/status'
  resources :restaurants do
    resources :reviews, only: [ :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = %w[chinese italian japanese french belgian]
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES, message: "%{value} is not a valid category" }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }, :inclusion => { :in => 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  
  def index
    @restaurants = Restaurant.all
    # render
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was created successfully!"
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was updated!"
    else 
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant was deleted!"
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.new(review_params)
    # => #<Review:0x00007fbbbc035348 id: nil, content: "Great!", rating: nil, restaurant_id: 1, created_at: nil, updated_at: nil>
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to @restaurant, notice: "Review was deleted!"
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  
    <!-- [...] -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

<!-- app/views/layouts/application.html.erb -->
<head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
</head>

app/views/restaurants/index.html.erb
<h1>My restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Address: <%= @restaurant.address %></p>
<p>Phone: <%= @restaurant.phone_number %></p>
<p>All Reviews</p>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %> | <%= review.rating %> <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete, data: { confirm: "Are you sure?"} %></li>
  <% end %>
</ul>

<p>Please add your review below:</p>
<hr />
<%= form_for [@restaurant, @review] do |f| %>
  <div>
    <%= f.label :content %><br />
    <%= f.text_area :content, { rows: "5" } %></div>
  <div>
  <div>
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>NEW Review</h1>